<?php
/*
Plugin Name: Nice Titles
Plugin URI: http://showfom.com/nice-titles-wordpress-plugin/
Description: Nice Titles on your Wordpress Blog based on the Nice Titles script by <a href="http://www.kryogenix.org/code/browser/nicetitle/" title="Nice Titles">kryogenix.org</a>.
Version: 1.0
Author: Showfom
Author URI: http://showfom.com/

**********************************************************************
Copyright (c) 2009 Showfom
Released under the terms of the GNU GPL: http://www.gnu.org/licenses/gpl.txt

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
**********************************************************************

Installation: Upload the folder "nice-titles" with its contents to "wp-content/plugins/"  and activate the plugin in your admin panel.
*/

function NiceTitles() {
  /*  Path for snow */
	$ntPath = get_option('siteurl').'/wp-content/plugins/nice-titles/';
	$ntJS .= '<!-- Generated by Nice Titles 1.0 -->'."\n";
	$ntJS .= '<script type="text/javascript" src="'.$ntPath.'nicetitle.js"></script>'."\n";
	$ntJS .= '<link rel="stylesheet" href="'.$ntPath.'nicetitle.css" />'."\n";
	print($ntJS);
}
add_action('wp_head', 'NiceTitles');
?>
